build: Prevent the redefinition of `stdlib_pch` target in release builds
```
  -- Precompiled headers were enabled
  CMake Error at build-support/macros-and-definitions.cmake:1272 (add_library):
    add_library cannot create ALIAS target "stdlib_pch" because another target
    with the same name already exists.
  Call Stack (most recent call first):
    CMakeLists.txt:149 (process_options)
```

Signed-off-by: Rui Chen <rui@chenrui.dev>